.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).

.. # Sourcecode on GitHub
.. |SHIELD:svg:Sphinx-github| image:: https://img.shields.io/badge/pyTooling-Sphinx-63bf7f?longCache=true&style=flat-square&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.Sphinx
.. |SHIELD:png:Sphinx-github| image:: https://raster.shields.io/badge/pyTooling-Sphinx-63bf7f?longCache=true&style=flat-square&logo=GitHub
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.Sphinx

.. # Code license
.. |SHIELD:svg:Sphinx-src-license| image:: https://img.shields.io/pypi/l/pyTooling.Sphinx?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:Sphinx-src-license| image:: https://raster.shields.io/pypi/l/pyTooling.Sphinx?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.Sphinx/blob/main/LICENSE.md

.. # Documentation
.. |SHIELD:svg:Sphinx-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2FpyTooling.Sphinx&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2FpyTooling.Sphinx%2Findex.html
   :alt: Documentation
   :height: 22
   :target: https://pyTooling.github.io/pyTooling.Sphinx/
.. |SHIELD:png:Sphinx-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2FpyTooling.Sphinx&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2FpyTooling.Sphinx%2Findex.html
   :alt: Documentation
   :height: 22
   :target: https://pyTooling.github.io/pyTooling.Sphinx/

.. # Documentation license
.. |SHIELD:svg:Sphinx-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation license
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:Sphinx-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation license
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.Sphinx/blob/main/doc/Doc-License.rst

.. # PyPI
.. |SHIELD:svg:Sphinx-pypi-tag| image:: https://img.shields.io/pypi/v/pyTooling.Sphinx?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI
   :height: 22
   :target: https://pypi.org/project/pyTooling.Sphinx/
.. |SHIELD:png:Sphinx-pypi-tag| image:: https://raster.shields.io/pypi/v/pyTooling.Sphinx?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI
   :height: 22
   :target: https://pypi.org/project/pyTooling.Sphinx/

.. # PyPI - Status
.. |SHIELD:svg:Sphinx-pypi-status| image:: https://img.shields.io/pypi/status/pyTooling.Sphinx?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
   :target: https://pypi.org/project/pyTooling.Sphinx/
.. |SHIELD:png:Sphinx-pypi-status| image:: https://raster.shields.io/pypi/status/pyTooling.Sphinx?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
   :target: https://pypi.org/project/pyTooling.Sphinx/

.. # PyPI - Python Version
.. |SHIELD:svg:Sphinx-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyTooling.Sphinx?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
   :target: https://pypi.org/project/pyTooling.Sphinx/
.. |SHIELD:png:Sphinx-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyTooling.Sphinx?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
   :target: https://pypi.org/project/pyTooling.Sphinx/

.. # GitHub Workflow - Build and Test Status
.. |SHIELD:svg:Sphinx-gha-test| image:: https://img.shields.io/github/actions/workflow/status/pyTooling/pyTooling.Sphinx/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=build%20and%20test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.Sphinx/actions/workflows/Pipeline.yml
.. |SHIELD:png:Sphinx-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/pyTooling/pyTooling.Sphinx/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=build%20and%20test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.Sphinx/actions/workflows/Pipeline.yml

.. # Libraries.io status for latest release
.. |SHIELD:svg:Sphinx-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyTooling.Sphinx?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling.Sphinx
.. |SHIELD:png:Sphinx-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyTooling.Sphinx?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling.Sphinx

.. # Codecov - Branch Coverage
.. |SHIELD:svg:Sphinx-codecov-coverage| image:: https://img.shields.io/codecov/c/github/pyTooling/pyTooling.Sphinx?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyTooling.Sphinx
.. |SHIELD:png:Sphinx-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/pyTooling/pyTooling.Sphinx?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyTooling.Sphinx
